### ISSUE TITLE
Can you help upgrade the plugin files?

### ISSUE THREAD

**Issue by huizhoujava** [nidheeshdas/bower-pdfkit#1]
pdfkit has been released under version 0.7.1 https://github.com/devongovett/pdfkit/releases, blob-stream has been released under version 0.1.3 https://github.com/devongovett/blob-stream/releases,
so can you help upgrade these two plugins so I can install the latest version with command "bower install bower-pdfkit"?

**Comment by nidheeshdas** [comment]
Updated. Thanks for notifying me.

**Comment by huizhoujava** [comment]
Thanks!
